### ISSUE TITLE
Incompatability With Unpaused Menus

### ISSUE THREAD

**Issue by Halliphax** [Ryan-rsm-McKenzie/QuickLootRE#99] opened 2020-10-13 13:05 UTC
Slight incompatibility with mods that unpause the game menu i.e https://www.nexusmods.com/skyrimspecialedition/mods/27859 (though that mod is a continuation of your original mod https://www.nexusmods.com/skyrimspecialedition/mods/21374).

Issue is best recreated without SkyUI or HideSkyUI, though the problem can occur with the normal SkyUI menus. It's most common with Container menus but can happen with any unpaused menu (i.e favourites menu).

Recreation steps/prerequisites: 

Install latest QuickLoot version
Install Skyrim Souls
(Optional) HideSkyUI 

1) Hover over a container or body that has items in it so that QuickLoot menu appears
2) Press corresponding button to enter full Container menu 
3) Enter/leave various subcategories (i.e All, Weapons, Armors etc) and repeat in quick fashion

Following the steps above, eventually the Container menu will soft lock so you can't leave (unless the container is emptied or you force a load screen i.e COC console command).  
The same has happened to me with the favourites menu but it's trickier to recreate, I believe the key is having the QuickLoot menu on screen while entering an unpaused menu state. It feels as though the QuickLoot menu still has control over the button input due to the unpaused menus not being "real" menus as far as the game engine is concerned  (hence why the soft lock happens?). 

Oddly, this behaviour didn't happen with the original version of QuickLoot (https://www.nexusmods.com/skyrimspecialedition/mods/35951)

**Comment by Halliphax** [comment] 2020-10-13 13:28
Additionally, if you try and recreate the above with a container that doesn't show QuickLoot (i.e mods that add custom containers that always display "Search" regardless of QuickLoot being installed) the problem can't be recreated, hence my assumption about control being retained by QuickLoot somewhere.

**Comment by Ryan-rsm-McKenzie** [comment] 2020-10-13 21:26
This is an issue with skyrim souls itself

**Comment by Vermunds** [comment] 2021-01-09 16:35
This should be fixed in the latest version of Skyrim Souls. Though can't confirm it, I couldn't reproduce this in the first place.

**Closed** 2021-01-09 16:37 UTC
Labels: incompatibility
